// ------- Definición de logros -------
// Nota: todos cuentan dentro de la run actual. Se desbloquean y guardan con fecha.
export const ACHIEVEMENTS = [{
        id: 'typical-start',
        title: 'Un comienzo típico',
        desc: 'Empieza la primera misión sin compañero y recibe un Pokémon para entrenadores principiantes.',
        tier: 'Superball',
        domain: 'pokeDiscover',
        scope: 'run',
        event: 'manual',
        check: (m) => m?.id === 'typical-start',
    }, {
        id: 'first-mission',
        title: '¡Primera misión!',
        desc: 'Completa tu primer encargo de campo para el profesor Alcanfor.',
        tier: 'Superball',
        domain: 'pokeDiscover',
        scope: 'run',
        event: 'manual',
        check: (m) => m?.id === 'first-mission',
    }, {
        id: 'daily-trivia-streak-7',
        title: 'Semana de sobresalientes',
        desc: 'Aprueba el examen diario siete días seguidos.',
        tier: 'Ultraball',
        domain: 'mode',
        modeId: 'daily-trivia',
        scope: 'run',
        event: 'manual',
        check: (m) => m?.id === 'daily-trivia-streak-7',
    }, {
        id: 'daily-trivia-complete',
        title: 'Alumno aplicado',
        desc: 'Aprueba tu primer examen diario.',
        tier: 'Superball',
        domain: 'mode',
        modeId: 'daily-trivia',
        scope: 'run',
        event: 'manual',
        check: (m) => m?.id === 'daily-trivia-complete',
    }, {
        id: 'themed-challenge-triad',
        title: 'Tres prismas del saber',
        desc: 'Completa al menos un reto de generación, uno de tipo y uno de familia.',
        tier: 'Ultraball',
        domain: 'mode',
        modeId: 'themed-challenges',
        scope: 'run',
        event: 'manual',
        check: (m) => m?.id === 'themed-challenge-triad',
    }, {
        id: 'themed-challenge-complete',
        title: 'Conocimiento temático',
        desc: 'Completa tu primer reto temático.',
        tier: 'Superball',
        domain: 'mode',
        modeId: 'themed-challenges',
        scope: 'run',
        event: 'manual',
        check: (m) => m?.id === 'themed-challenge-complete',
    }, {
        id: 'whos-that-pokemon-perfect',
        title: 'Vista de Noctowl',
        desc: 'Alcanza una racha de diez en ¿Quién es ese Pokémon?',
        tier: 'Ultraball',
        domain: 'mode',
        modeId: 'whos-that-pokemon',
        scope: 'run',
        event: 'manual',
        check: (m) => m?.id === 'whos-that-pokemon-perfect',
    }, {
        id: 'whos-that-pokemon-complete',
        title: '¡Es...!',
        desc: 'Termina una racha de ¿Quién es ese Pokémon?',
        tier: 'Superball',
        domain: 'mode',
        modeId: 'whos-that-pokemon',
        scope: 'run',
        event: 'manual',
        check: (m) => m?.id === 'whos-that-pokemon-complete',
    }, {
        id: 'timed-collector-complete',
        title: 'A contrarreloj',
        desc: 'Termina una sesión del Coleccionista de logros.',
        tier: 'Superball',
        domain: 'mode',
        modeId: 'timed-collector',
        scope: 'run',
        event: 'manual',
        check: (m) => m?.id === 'timed-collector-complete',
    }, {
        id: 'delibird-gift-claim',
        title: 'El regalo de Delibird',
        desc: 'Encuentra el regalo bueno durante el modo Delibird.',
        tier: 'Superball',
        domain: 'mode',
        scope: 'run',
        event: 'manual',
        check: (m) => m?.id === 'delibird-gift-claim',
    },
    {
        id: 'fast-3in20',
        title: 'Más rápido que Gary',
        desc: 'Haz 3 aciertos seguidos en los primeros 20 s.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.streak >= 3 && ctx.msFromStart() <= 20000,
    },
    {
        id: 'profesor-5streak',
        title: 'Profesor Pokémon',
        desc: 'Logra racha x5 sin fallos.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.streak >= 5 && ctx.fails === 0,
    },
    {
        id: 'gengar-winks-3',
        title: 'Gengar te guiña',
        desc: 'Adivina 3 Pokémon de tipo fantasma seguidos.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.lastGhostChain >= 3,
    },
    {
        id: 'long-name-12',
        title: 'Nombre kilométrico',
        desc: 'Adivina un Pokémon con 12+ letras.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m) => ((m?.name || '').replace(/[\s\-·_']/g, '').length >= 12),
    },
    {
        id: 'starters-one-gen',
        title: 'Iniciales',
        desc: 'Acierta en la misma run los 3 iniciales de una gen.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => Number.isInteger(m?.gen) && !!ctx.startersHitByGen.get(m.gen) && ctx.startersHitByGen.get(m.gen).size >= 3,
    },
    {
        id: 'first-blood',
        title: 'Primer paso',
        desc: 'Acierta tu primer Pokémon de la run.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.correctTotal === 1,
    },
    {
        id: 'classic-start-pikachu',
        title: 'Un inicio clásico',
        desc: 'Haz que Pikachu sea el primer Pokémon descubierto de la run.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.correctTotal === 1 && Number(m?.id) === 25,
    },
    {
        id: 'fossil-3',
        title: 'Fósiles al poder',
        desc: 'Descubre 3 Pokémon fósil.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.fossilCount >= 3,
    },
    {
        id: 'arceus',
        title: 'Dios de dioses',
        desc: 'Descubre a Arceus.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: (m) => (m?.name || '').toLowerCase().replace(/\s/g, '') === 'arceus',
    },
    {
        id: 'faster-than-ash',
        title: 'Más rápido que Ash',
        desc: 'Descubre a cualquier inicial antes que a Pikachu.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => !!m?.isStarter && !ctx.hasGuessedName('pikachu'),
    },
    {
        id: 'ghost-3',
        title: 'Bandada en ataque',
        desc: 'Descubre 3 Pokémon fantasma.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('ghost') >= 3,
    },
    {
        id: 'ghost-10',
        title: 'Fantasmada',
        desc: 'Descubre 10 Pokémon fantasma.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('ghost') >= 10,
    },
    {
        id: 'flying-3',
        title: 'Bandada en ataque',
        desc: 'Descubre 3 Pokémon volador.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('flying') >= 3,
    },
    {
        id: 'flying-10',
        title: 'Máquina Oculta: Vuelo',
        desc: 'Descubre 10 Pokémon volador.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('flying') >= 10,
    },
    {
        id: 'poison-3',
        title: '¡Qué mal olor!',
        desc: 'Descubre 3 Pokémon veneno.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('poison') >= 3,
    },
    {
        id: 'poison-10',
        title: 'Ataque biológico',
        desc: 'Descubre 10 Pokémon veneno.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('poison') >= 10,
    },
    {
        id: 'ground-3',
        title: 'No me pises',
        desc: 'Descubre 3 Pokémon tierra.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('ground') >= 3,
    },
    {
        id: 'ground-10',
        title: 'Sacudida sísmica',
        desc: 'Descubre 10 Pokémon tierra.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('ground') >= 10,
    },
    {
        id: 'dark-3',
        title: 'Gafas oscuras',
        desc: 'Descubre 3 Pokémon siniestro.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('dark') >= 3,
    },
    {
        id: 'dark-10',
        title: 'El más edgy',
        desc: 'Descubre 10 Pokémon siniestro.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('dark') >= 10,
    },
    {
        id: 'rock-3',
        title: 'Piedras en el camino',
        desc: 'Descubre 3 Pokémon roca.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('rock') >= 3,
    },
    {
        id: 'rock-10',
        title: 'Geo-duda resuelta',
        desc: 'Descubre 10 Pokémon roca.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('rock') >= 10,
    },
    {
        id: 'psychic-3',
        title: '¡Teletransporte!',
        desc: 'Descubre 3 Pokémon psíquico.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('psychic') >= 3,
    },
    {
        id: 'psychic-10',
        title: 'Volar sin alas',
        desc: 'Descubre 10 Pokémon psíquico.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('psychic') >= 10,
    },
    {
        id: 'grass-3',
        title: 'Riega-me',
        desc: 'Descubre 3 Pokémon planta.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('grass') >= 3,
    },
    {
        id: 'grass-10',
        title: 'Fábrica de perfumes',
        desc: 'Descubre 10 Pokémon planta.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('grass') >= 10,
    },
    {
        id: 'normal-3',
        title: 'Meh',
        desc: 'Descubre 3 Pokémon normal.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('normal') >= 3,
    },
    {
        id: 'normal-10',
        title: 'Que sí que no tienes debilidades...',
        desc: 'Descubre 10 Pokémon normal.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('normal') >= 10,
    },
    {
        id: 'fighting-3',
        title: 'Unga unga',
        desc: 'Descubre 3 Pokémon lucha.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('fighting') >= 3,
    },
    {
        id: 'fighting-10',
        title: 'Más campeón que Primeape',
        desc: 'Descubre 10 Pokémon lucha.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('fighting') >= 10,
    },
    {
        id: 'ice-3',
        title: 'Clima ártico',
        desc: 'Descubre 3 Pokémon hielo.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('ice') >= 3,
    },
    {
        id: 'ice-10',
        title: 'Uno que es ártico',
        desc: 'Descubre 10 Pokémon hielo.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('ice') >= 10,
    },
    {
        id: 'fairy-3',
        title: 'Ooooh',
        desc: 'Descubre 3 Pokémon hada.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('fairy') >= 3,
    },
    {
        id: 'fairy-10',
        title: 'Trae un dragón',
        desc: 'Descubre 10 Pokémon hada.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('fairy') >= 10,
    },
    {
        id: 'fire-3',
        title: 'Enciéndeme la hoguera',
        desc: 'Descubre 3 Pokémon fuego.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('fire') >= 3,
    },
    {
        id: 'fire-10',
        title: 'Hágame caso, Charmeleon',
        desc: 'Descubre 10 Pokémon fuego.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('fire') >= 10,
    },
    {
        id: 'electric-3',
        title: 'Ya vale con los Pokachos',
        desc: 'Descubre 3 Pokémon eléctrico.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('electric') >= 3,
    },
    {
        id: 'electric-10',
        title: '¿Placaje eléctrico?',
        desc: 'Descubre 10 Pokémon eléctrico.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('electric') >= 10,
    },
    {
        id: 'dragon-3',
        title: '¿Y Charizard qué?',
        desc: 'Descubre 3 Pokémon dragón.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('dragon') >= 3,
    },
    {
        id: 'dragon-10',
        title: 'Soy tu favorito',
        desc: 'Descubre 10 Pokémon dragón.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('dragon') >= 10,
    },
    {
        id: 'bug-3',
        title: 'Otro gusano más',
        desc: 'Descubre 3 Pokémon bicho.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('bug') >= 3,
    },
    {
        id: 'bug-10',
        title: 'Bien, un tipo útil',
        desc: 'Descubre 10 Pokémon bicho.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('bug') >= 10,
    },
    {
        id: 'water-3',
        title: 'Ay, no me chorrees',
        desc: 'Descubre 3 Pokémon agua.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('water') >= 3,
    },
    {
        id: 'water-10',
        title: '¿Burbujas, en serio?',
        desc: 'Descubre 10 Pokémon agua.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('water') >= 10,
    },
    {
        id: 'steel-3',
        title: 'Peso pesado',
        desc: 'Descubre 3 Pokémon acero.',
        tier: 'Pokeball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('steel') >= 3,
    },
    {
        id: 'steel-10',
        title: 'Más pesado aún',
        desc: 'Descubre 10 Pokémon acero.',
        tier: 'Superball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('steel') >= 10,
    },
    {
        id: 'ghost-30',
        title: 'Más fantasma que un cuñao',
        desc: 'Descubre 30 Pokémon fantasma.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('ghost') >= 30,
    },
    {
        id: 'ghost-all',
        title: 'Eres el Sr. Fuji',
        desc: 'Descubre todos los Pokémon fantasma (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('ghost') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('ghost')),
    },
    {
        id: 'flying-30',
        title: 'Monta en tu Charizard',
        desc: 'Descubre 30 Pokémon volador.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('flying') >= 30,
    },
    {
        id: 'flying-all',
        title: 'El límite ya no es el cielo',
        desc: 'Descubre todos los Pokémon volador (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('flying') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('flying')),
    },
    {
        id: 'poison-30',
        title: 'Nube tóxica',
        desc: 'Descubre 30 Pokémon veneno.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('poison') >= 30,
    },
    {
        id: 'poison-all',
        title: 'Antídoto universal',
        desc: 'Descubre todos los Pokémon veneno (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('poison') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('poison')),
    },
    {
        id: 'ground-30',
        title: 'Terrateniente',
        desc: 'Descubre 30 Pokémon tierra.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('ground') >= 30,
    },
    {
        id: 'ground-all',
        title: 'Sismólogo',
        desc: 'Descubre todos los Pokémon tierra (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('ground') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('ground')),
    },
    {
        id: 'dark-30',
        title: 'Media noche',
        desc: 'Descubre 30 Pokémon siniestro.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('dark') >= 30,
    },
    {
        id: 'dark-all',
        title: 'Se hace de noche',
        desc: 'Descubre todos los Pokémon siniestro (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('dark') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('dark')),
    },
    {
        id: 'rock-30',
        title: 'Cantera abierta',
        desc: 'Descubre 30 Pokémon roca.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('rock') >= 30,
    },
    {
        id: 'rock-all',
        title: 'Geólogo jefe',
        desc: 'Descubre todos los Pokémon roca (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('rock') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('rock')),
    },
    {
        id: 'psychic-30',
        title: 'Telepatía a full',
        desc: 'Descubre 30 Pokémon psíquico.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('psychic') >= 30,
    },
    {
        id: 'psychic-all',
        title: 'Mente colmena',
        desc: 'Descubre todos los Pokémon psíquico (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('psychic') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('psychic')),
    },
    {
        id: 'grass-30',
        title: 'Vivero portátil',
        desc: 'Descubre 30 Pokémon planta.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('grass') >= 30,
    },
    {
        id: 'grass-all',
        title: 'Jardín botánico',
        desc: 'Descubre todos los Pokémon planta (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('grass') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('grass')),
    },
    {
        id: 'normal-30',
        title: 'Vida cotidiana',
        desc: 'Descubre 30 Pokémon normal.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('normal') >= 30,
    },
    {
        id: 'normal-all',
        title: 'Costumbrista',
        desc: 'Descubre todos los Pokémon normal (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('normal') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('normal')),
    },
    {
        id: 'fighting-30',
        title: 'Guantes puestos',
        desc: 'Descubre 30 Pokémon lucha.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('fighting') >= 30,
    },
    {
        id: 'fighting-all',
        title: 'Campeón de dojo',
        desc: 'Descubre todos los Pokémon lucha (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('fighting') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('fighting')),
    },
    {
        id: 'ice-30',
        title: 'Frente frío',
        desc: 'Descubre 30 Pokémon hielo.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('ice') >= 30,
    },
    {
        id: 'ice-all',
        title: 'Edad de hielo',
        desc: 'Descubre todos los Pokémon hielo (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('ice') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('ice')),
    },
    {
        id: 'fairy-30',
        title: 'Polvo de hadas',
        desc: 'Descubre 30 Pokémon hada.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('fairy') >= 30,
    },
    {
        id: 'fairy-all',
        title: 'Corte de cinta',
        desc: 'Descubre todos los Pokémon hada (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('fairy') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('fairy')),
    },
    {
        id: 'fire-30',
        title: 'Hoguera eterna',
        desc: 'Descubre 30 Pokémon fuego.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('fire') >= 30,
    },
    {
        id: 'fire-all',
        title: 'Volcán activo',
        desc: 'Descubre todos los Pokémon fuego (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('fire') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('fire')),
    },
    {
        id: 'electric-30',
        title: 'Tensión máxima',
        desc: 'Descubre 30 Pokémon eléctrico.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('electric') >= 30,
    },
    {
        id: 'electric-all',
        title: 'Red eléctrica',
        desc: 'Descubre todos los Pokémon eléctrico (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('electric') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('electric')),
    },
    {
        id: 'dragon-30',
        title: 'Sangre de dragón',
        desc: 'Descubre 30 Pokémon dragón.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('dragon') >= 30,
    },
    {
        id: 'dragon-all',
        title: 'Aliento ancestral',
        desc: 'Descubre todos los Pokémon dragón (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('dragon') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('dragon')),
    },
    {
        id: 'bug-30',
        title: 'Plaga bíblica',
        desc: 'Descubre 30 Pokémon bicho.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('bug') >= 30,
    },
    {
        id: 'bug-all',
        title: 'Entomólogo supremo',
        desc: 'Descubre todos los Pokémon bicho (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('bug') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('bug')),
    },
    {
        id: 'water-30',
        title: 'Océano abierto',
        desc: 'Descubre 30 Pokémon agua.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('water') >= 30,
    },
    {
        id: 'water-all',
        title: 'Atlante',
        desc: 'Descubre todos los Pokémon agua (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('water') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('water')),
    },
    {
        id: 'steel-30',
        title: 'Blindaje total',
        desc: 'Descubre 30 Pokémon acero.',
        tier: 'Ultraball',
        scope: 'run',
        event: 'guess',
        check: (m, ctx) => ctx.typeCount('steel') >= 30,
    },
    {
        id: 'steel-all',
        title: 'Forjador legendario',
        desc: 'Descubre todos los Pokémon acero (gens activas).',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('steel') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('steel')),
    },
    {
        id: 'all-poison',
        title: 'Maestro tóxico',
        desc: 'Completa todos los Pokémon de tipo veneno de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('poison') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('poison')),
    },
    {
        id: 'all-fire',
        title: 'Maestro ígneo',
        desc: 'Completa todos los Pokémon de tipo fuego de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('fire') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('fire')),
    },
    {
        id: 'all-water',
        title: 'Maestro acuático',
        desc: 'Completa todos los Pokémon de tipo agua de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('water') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('water')),
    },
    {
        id: 'all-grass',
        title: 'Maestro botánico',
        desc: 'Completa todos los Pokémon de tipo planta de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('grass') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('grass')),
    },
    {
        id: 'all-electric',
        title: 'Maestro voltáico',
        desc: 'Completa todos los Pokémon de tipo eléctrico de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('electric') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('electric')),
    },
    {
        id: 'all-psychic',
        title: 'Maestro mental',
        desc: 'Completa todos los Pokémon de tipo psíquico de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('psychic') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('psychic')),
    },
    {
        id: 'all-rock',
        title: 'Maestro geólogo',
        desc: 'Completa todos los Pokémon de tipo roca de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('rock') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('rock')),
    },
    {
        id: 'all-ground',
        title: 'Maestro sísmico',
        desc: 'Completa todos los Pokémon de tipo tierra de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('ground') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('ground')),
    },
    {
        id: 'all-flying',
        title: 'Maestro de los cielos',
        desc: 'Completa todos los Pokémon de tipo volador de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('flying') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('flying')),
    },
    {
        id: 'all-bug',
        title: 'Maestro entomólogo',
        desc: 'Completa todos los Pokémon de tipo bicho de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('bug') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('bug')),
    },
    {
        id: 'all-fighting',
        title: 'Maestro de artes marciales',
        desc: 'Completa todos los Pokémon de tipo lucha de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('fighting') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('fighting')),
    },
    {
        id: 'all-normal',
        title: 'Maestro costumbrista',
        desc: 'Completa todos los Pokémon de tipo normal de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('normal') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('normal')),
    },
    {
        id: 'all-dark',
        title: 'Maestro sombrío',
        desc: 'Completa todos los Pokémon de tipo siniestro de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('dark') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('dark')),
    },
    {
        id: 'all-fairy',
        title: 'Maestro de los cuentos',
        desc: 'Completa todos los Pokémon de tipo hada de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('fairy') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('fairy')),
    },
    {
        id: 'all-steel',
        title: 'Maestro herrero',
        desc: 'Completa todos los Pokémon de tipo acero de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('steel') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('steel')),
    },
    {
        id: 'all-ice',
        title: 'Maestro glaciar',
        desc: 'Completa todos los Pokémon de tipo hielo de las gens activas.',
        tier: 'MasterBall',
        scope: 'run',
        event: 'guess',
        check: async (m, ctx) => (m?.types || []).includes('ice') && !!ctx.isTypeComplete && (await ctx.isTypeComplete('ice')),
    },
];
